name: Deploy .NET Web App to Azure App Service

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # or your target framework version

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Step 4: Build the project
      - name: Build
        run: dotnet build --configuration Release --no-restore

      # Step 5: Publish the app
      - name: Publish app
        run: dotnet publish --configuration Release --output ./publish

      # Step 6: Deploy to Azure App Service
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'SCSBEAPI'  # 👈 your Azure App Service name
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}  # 👈 secret name
          package: ./publish
